image: rocker/tidyverse

default:
  tags:
    - docker
    - shell
    - specific

stages:
  - build
  - test
  - deploy

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"

building:
  stage: build
  script:
    - docker info
    - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR
    - R -e 'remotes::install_deps(dependencies = TRUE, lib = Sys.getenv("R_LIBS_USER"))'
    - R -e 'devtools::check(vignettes = FALSE, check_dir = Sys.getenv("CHECK_DIR"), args = "--no-tests")'
  cache:
    paths:
      - $R_LIBS_USER

testing:
    stage: test
    allow_failure: true
    when: on_success
    only:
        - master
    script:
        - Rscript -e 'install.packages("DT")'
        - Rscript -e 'covr::gitlab(quiet = FALSE)'
    artifacts:
        paths:
            - public

# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

pages:
    stage: deploy
    dependencies:
        - testing
    script:
        - ls
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
